### ISSUE TITLE
[MC1.14] Crash when you die

### ISSUE THREAD

**Issue by Gbergz** [Insane96/ProgressiveBosses#44]
Crash report: [paste.ee](https://paste.ee/p/lgGmp)

Game crashes when you die.
Read the crashlog and your modname appeared might aswell report it, if its your mod which im not sure about.

Forge ver: 28.0.92
Game ver: 1.14.4

**Comment by Insane96** [comment]
Need more infos

**Comment by Riddler76** [comment]
java.lang.NoSuchMethodError: net.minecraft.entity.player.PlayerEntity.getEntityData()Lnet/minecraft/nbt/CompoundNBT;
	at insane96mcp.progressivebosses.events.PlayerClone.eventPlayerClone(PlayerClone.java:17) ~[?:2.1.1] {}
	at net.minecraftforge.eventbus.ASMEventHandler_17_PlayerClone_eventPlayerClone_Clone.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPlayerClone(ForgeEventFactory.java:462) ~[?:?] {}
	at net.minecraft.entity.player.ServerPlayerEntity.func_193104_a(ServerPlayerEntity.java:1041) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.management.PlayerList.func_72368_a(PlayerList.java:404) ~[?:?] {}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147342_a(ServerPlayNetHandler.java:1097) ~[?:?] {}
	at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:31) ~[?:?] {}
	at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:8) ~[?:?] {}
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:33) ~[?:?] {xf:OptiFine:default}
	at net.minecraft.network.PacketThreadUtil$$Lambda$5369/761152230.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:170) ~[?:?] {pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:135) ~[?:?] {pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:115) ~[?:?] {pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:678) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626) [?:?] {pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

**Comment by Riddler76** [comment]
[10:58:40] [Server thread/ERROR]: Exception caught during firing event: net.minecraft.entity.player.PlayerEntity.getEntityData()Lnet/minecraft/nbt/CompoundNBT;
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: class insane96mcp.progressivebosses.events.PlayerClone eventPlayerClone(Lnet/minecraftforge/event/entity/player/PlayerEvent$Clone;)V
		2: ASM: class its_meow.betteranimalsplus.common.CommonEventHandler onPlayerRespawn(Lnet/minecraftforge/event/entity/player/PlayerEvent$Clone;)V
		3: ASM: mcjty.theoneprobe.ForgeEventHandlers@2d776d14 onPlayerCloned(Lnet/minecraftforge/event/entity/player/PlayerEvent$Clone;)V
java.lang.NoSuchMethodError: net.minecraft.entity.player.PlayerEntity.getEntityData()Lnet/minecraft/nbt/CompoundNBT;
	at insane96mcp.progressivebosses.events.PlayerClone.eventPlayerClone(PlayerClone.java:17)
	at net.minecraftforge.eventbus.ASMEventHandler_17_PlayerClone_eventPlayerClone_Clone.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.event.ForgeEventFactory.onPlayerClone(ForgeEventFactory.java:462)
	at net.minecraft.entity.player.ServerPlayerEntity.func_193104_a(ServerPlayerEntity.java:1041)
	at net.minecraft.server.management.PlayerList.func_72368_a(PlayerList.java:404)
	at net.minecraft.network.play.ServerPlayNetHandler.func_147342_a(ServerPlayNetHandler.java:1097)
	at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:31)
	at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:8)
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:33)
	at net.minecraft.network.PacketThreadUtil$$Lambda$5369/761152230.run(Unknown Source)
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:170)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:135)
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699)
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:115)
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:678)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626)
	at java.lang.Thread.run(Thread.java:745)

[10:58:40] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: net.minecraft.entity.player.PlayerEntity.getEntityData()Lnet/minecraft/nbt/CompoundNBT;
	at insane96mcp.progressivebosses.events.PlayerClone.eventPlayerClone(PlayerClone.java:17) ~[?:2.1.1]
	at net.minecraftforge.eventbus.ASMEventHandler_17_PlayerClone_eventPlayerClone_Clone.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerClone(ForgeEventFactory.java:462) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_193104_a(ServerPlayerEntity.java:1041) ~[?:?]
	at net.minecraft.server.management.PlayerList.func_72368_a(PlayerList.java:404) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147342_a(ServerPlayNetHandler.java:1097) ~[?:?]
	at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:31) ~[?:?]
	at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:8) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:33) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$5369/761152230.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:170) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:135) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:115) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:678) ~[?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]

**Comment by Riddler76** [comment]
The game crash when you click on Respawn

**Comment by Insane96** [comment]
Use pastebin and send the full crashlog

**Comment by Insane96** [comment]
Also I asked for more infos not the same crashlog, when / how did you die?

**Comment by Riddler76** [comment]
I try this one when a mob kill me. The crash come only when you click on respawn button.

I resend you log cleanely ;)

Crash report : https://pastebin.com/BjMCYSpn
Log : https://pastebin.com/EDpwbqUX

**Comment by Insane96** [comment]
Ok, seems easy enough to fix

**Comment by ProsperCraft** [comment]
Same here - 
Crashlog- https://gist.github.com/ProsperCraft/5013a444029b81dee271f8adde77acbe

Forge 1.0.6

[latest.log](https://github.com/Insane96/ProgressiveBosses/files/3622677/latest.log)

Modpack- 
https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

**Comment by Insane96** [comment]
Forge 1.0.6 doesn't exist.

**Comment by Riddler76** [comment]
Forge: net.minecraftforge:28.1.6

**Comment by ProsperCraft** [comment]
Just to follow up- it no longer crashes once this was removed from the pack.
